services:
  db-invoice:
    image: postgres:16
    container_name: db-invoice-container
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    volumes:
      - ./invoice_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - invoice

networks:
  invoice: